version: "3"

services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev123
    ports:
      - "27017:27017"
    volumes:
      - /mongodb:/data/db
